spring:
  application:
    name: msvc-tesis

  data:
    mongodb:
      uri: ${DB_URL:mongodb://localhost:27017}
      database: ${DB_NAME:msvc_tesis}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    disable-swagger-default-url: true
    operationsSorter: method
